spring.application.name=virtualstudyroom

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} level=%-5level app=${spring.application.name} correlationId=%X{correlationId:-na} logger=%logger{36} msg="%msg"%n%wEx

#spring.datasource.url=jdbc:postgresql://localhost:5432/virtualstudyroom
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.datasource.url=jdbc:postgresql://virtualstudyroom.postgres.database.azure.com:5432/virtualstudyroom?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=rootroot1!

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=change-this-in-env-for-prod-change-this-in-env-for-prod
app.jwt.expiration-ms=86400000

#app.cors.allowed-origins=http://localhost:4200
app.cors.allowed-origins=https://wonderful-tree-02e36ee1e.1.azurestaticapps.net,https://wonderful-tree-02e36ee1e-preview.westus2.1.azurestaticapps.net,http://localhost:4200

app.rate-limit.room-create.max-requests=3
app.rate-limit.room-create.window-seconds=600
app.rate-limit.chat-send.max-requests=10
app.rate-limit.chat-send.window-seconds=10

app.chat.max-length=500

app.pomodoro.focus-seconds=1500
app.pomodoro.break-seconds=300

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
management.metrics.tags.application=${spring.application.name}
